### ISSUE TITLE
Suggestion, a wait loop for sway.service

### ISSUE THREAD

**Issue by freed00m** [gdamjan/sway-setup#2]
Just stumbled upon your dotfiles and like it.

Question? Does your systemd --user services run in correct order without fail?

When I implemented my [sway service](https://git.sr.ht/~freed00m/dotfiles/tree/master/item/.config/systemd/user/sway.service) a while ago I observed that sway will exits before fully initialize DISPLAY and WAYLAND_DISPLAY causing all sort of failures for services lika mako or wlsunset.

I've splitted sway to it's own sway-session-pre.target (doesn't haveto be though) and put a loop that pools the $WAYLAND_DISPLAY
```
ExecStartPost=%h/.config/systemd/user/sway-wait-for-wayland-display.sh
```
https://git.sr.ht/~freed00m/dotfiles/tree/master/item/.config/systemd/user/sway-wait-for-wayland-display.sh

I think it's neat as systemd will reports active ready after the sh scripts finds the variable making the After=sway-whatever not fail because it could not find initialized display.

**Comment by gdamjan** [comment]
> Question? Does your systemd --user services run in correct order without fail?

nothing starts until sway gets to the `exec "systemctl --user import-environment ; systemctl --user start sway-session.target"` line. at that point the environment is setup, sway is active, and the sway-session.target is started (it pulls wayland-session etc).

ps.
it would be so much nicer if sway supported this natively :cry:

**Comment by freed00m** [comment]
Ah I see, you are using graphical login manager that starts your custom .desktop file.


My approach is to remove the login manager and use the terminal login Agetty, when I login to /dev/tty1 sway is launched automatically by my systemd --user services :)

**Comment by gdamjan** [comment]
Even in that case the rest of the applications can be started just by the sway-session or wayland-session target (and not by the default.target).

**Comment by freed00m** [comment]
True, I just felt making the After=Sway.service work by polling the $WAYLAND_DISPLAY :)
